### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ickc** [ickc/bupc-install#1]
- [x] Add [UPC-to-C translator](http://upc.lbl.gov/download/dist-trans/README)
- [x] Use `gmake` if exists
- [x] configure install path such that sudo is not required.
- [ ] check for relative path in `-o`
- [x] refactor mkdir commands to function
- [ ] distribute binaries for Travis CI
